name: gate_survey_app
description: A smart survey app for gate installation planning.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.0 # For picking images from gallery/camera
  path_provider: ^2.1.3 # For getting temporary directory for images
  path: ^1.9.0 # For path manipulation
  csv: ^5.1.1 # For exporting data to CSV

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
