name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          python3-pip

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip virtualenv
        pip install buildozer cython==0.29.36

    - name: Configure Buildozer
      run: |
        buildozer init
        # Update buildozer.spec with our configuration
        echo '[app]' > buildozer.spec
        echo 'title = Gate Survey App' >> buildozer.spec
        echo 'package.name = gatesurvey' >> buildozer.spec
        echo 'package.domain = org.gatesurvey' >> buildozer.spec
        echo 'source.dir = .' >> buildozer.spec
        echo 'source.include_exts = py,png,jpg,kv' >> buildozer.spec
        echo 'source.include_patterns = assets/*' >> buildozer.spec
        echo 'version = 1.0.0' >> buildozer.spec
        echo 'requirements = python3,kivy==2.2.1,reportlab,plyer,android' >> buildozer.spec
        echo 'orientation = portrait' >> buildozer.spec
        echo 'osx.python_version = 3' >> buildozer.spec
        echo 'osx.kivy_version = 2.2.1' >> buildozer.spec
        echo 'fullscreen = 0' >> buildozer.spec
        echo 'android.permissions = CAMERA,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE' >> buildozer.spec
        echo 'android.api = 33' >> buildozer.spec
        echo 'android.minapi = 21' >> buildozer.spec
        echo 'android.ndk = 23b' >> buildozer.spec
        echo 'p4a.branch = master' >> buildozer.spec
        echo 'android.arch = armeabi-v7a' >> buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android release
        mkdir dist
        cp bin/*.apk dist/

    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: gate-survey-app
        path: dist/*.apk
        retention-days: 5