name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          python3-pip

    - name: Install Android SDK and NDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Install Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d ~/.android/cmdline-tools
        mv ~/.android/cmdline-tools/cmdline-tools ~/.android/cmdline-tools/latest
        
        # Install NDK 25b
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d ~/.android
        mv ~/.android/android-ndk-r25b ~/.android/android-ndk
        
        # Install SDK components
        yes | ~/.android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.android "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        ~/.android/cmdline-tools/latest/bin/sdkmanager --licenses || true

        # Set environment variables
        echo "ANDROID_HOME=$HOME/.android" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$HOME/.android/android-ndk" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/.android/cmdline-tools/latest/bin:$HOME/.android/platform-tools" >> $GITHUB_ENV

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip virtualenv
        pip install buildozer cython==0.29.36

    - name: Patch reportlab setup
      run: |
        # Force reportlab to skip problematic C extensions
        echo "REPORTLAB_NO_C_EXTENSIONS=1" >> $GITHUB_ENV
        sed -i "s|#android.ndk_path =.*|android.ndk_path = $HOME/.android/android-ndk|" buildozer.spec

    - name: Build APK
      run: |
        export PATH=$PATH:$ANDROID_HOME/build-tools/34.0.0
        export ANDROID_NDK_HOME=$HOME/.android/android-ndk
        export REPORTLAB_NO_C_EXTENSIONS=1
        buildozer -v android release
        mkdir dist
        cp bin/*.apk dist/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: gate-survey-app
        path: dist/*.apk
        retention-days: 5