name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          python3-pip

    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip virtualenv
        pip install buildozer cython==0.29.36

    - name: Configure Buildozer
      run: |
        buildozer init
        # Create minimal buildozer.spec
        cat << EOF > buildozer.spec
        [app]
        title = Gate Survey App
        package.name = gatesurvey
        package.domain = org.gatesurvey
        source.dir = .
        source.include_exts = py,png,jpg,kv
        source.include_patterns = assets/*
        version = 1.0.0
        requirements = python3,kivy==2.2.1,reportlab,plyer,android
        orientation = portrait
        osx.python_version = 3
        osx.kivy_version = 2.2.1
        fullscreen = 0
        android.permissions = CAMERA,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
        android.api = 33
        android.minapi = 21
        android.ndk = 23b
        p4a.branch = master
        android.arch = armeabi-v7a
        EOF

    - name: Build APK
      run: |
        buildozer -v android release
        mkdir dist
        cp bin/*.apk dist/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: gate-survey-app
        path: dist/*.apk
        retention-days: 5